### ISSUE TITLE
How to enable isomorphic rendering?

### ISSUE THREAD

**Issue by robhrt7** [szarouski/sourcejs-react#13]
Hi,

Could you please provide some hints, on how to enable isomorphic rendering? What should be added on client side?

**Comment by webuniverseio** [comment]
There is nothing special that you need to enable in sourcejs-react component to enable isomorphic rendering - all of that is handled by react and here is how:
Lets say you have an `App` component which takes some data-structure that is good enough to initialize the whole application. React will create an attribute for `App` which will look like `data-react-checksum="363833629"`. React will also wrap component's result html into div (1). To apply handlers and initialize React state on client side you need to call React.render on client side and pass two arguments - component with data and dom node. For dom node you want to use wrapper div (1). So code will look something like:

``` js
React.render(
    React.createElement(AppComponent, AppData),
    appComponentRootNode.parentNode
)
```

Because data for application startup is the same on both server and on client-side - react will create the same checksum, then on client side it will compare the values, because they will be the same, react will only apply event handlers on client side, without re-rendering the DOM. Later, when users will start interacting with the site, component's state will change and with the help of virtual dom only some of the dom branches will be affected.

Application code should be universal. For example you can't use jquery with code that will execute on server-side (for example `render` function). To initialize client-side specific functionality from component you want to use `componentDidMount`.

Not all applications use something global like App component as an only way to initialize component on client side. Most likely you want to initialize (make them isomorphic) only specific/interactive parts of your application. This means that we need to force react to generate a separate checksum for specific component and we can do that via `createFactory` and `renderToString`:

``` js
        var factory = React.createFactory(Button);
        var button = React.renderToString(factory({
            children: 'Btn Copy Gibson Reg; 1.2em'
        }));
        var buttonWhite = React.renderToString(factory({
            modifier: 'white',
            children: 'Btn Copy Gibson Reg; 1.2em'
        }));
```

The code above will generate separate checksums for buttons. Then on client side we'll do something like following:

``` js
React.render(
    React.createElement(Button, {
            children: 'Btn Copy Gibson Reg; 1.2em'
        }),
    buttonDomNode.parentNode
)
```

And that will allow us to use the same codebase for client and server sides.

Let me know if you need more details.
