### ISSUE TITLE
Nested required components not processed with babel in 2.0

### ISSUE THREAD

**Issue by robhrt7** [szarouski/sourcejs-react#14]
I'm requiring example button component into main `index.jsx`, and get and error about JSX code from included file:

```
react-styleguide-example/src/index.jsx:18

^
SyntaxError: Unexpected token <
```

I've tried to change babel conf, but nothing works, could you please try to run v.2.0 with https://github.com/sourcejs/react-styleguide-example?

**Comment by webuniverseio** [comment]
I cloned the repo and when I run `npm i && npm start` I get following in console:

```
Running SourceJS without user dir. This set-up should be used only for running tests.
```

I wonder if I need to setup something in addition? Meantime I'll create a user folder and try that way.

**Comment by webuniverseio** [comment]
With user folder I can see a spec page: 
![image](https://cloud.githubusercontent.com/assets/911388/10269793/86b8d0b8-6aae-11e5-8387-09674ed7a984.png)

**Comment by webuniverseio** [comment]
I can't reproduce the issue at the moment, so my guess is that glob pattern can't match require'd modules, perhaps something to do with symlinks or perhaps even with process.cwd()... If you can help me to setup things properly with `react-styleguide-example` I'll figure it out.

**Comment by robhrt7** [comment]
Just follow the set-up instructions, and update sourcejs-react dependency to latest one. If that won't help, maybe it's os specific issue, since on OSx process.cwd() could be different.

**Comment by sabrichu** [comment]
I'm seeing the same error when using a fresh checkout of the specs showcase https://github.com/sourcejs/example-specs-showcase:

<img width="1096" alt="screen shot 2016-04-01 at 4 35 23 pm" src="https://cloud.githubusercontent.com/assets/1165936/14224095/da6e69ec-f844-11e5-8fc8-75004d9649b3.png">

It renders fine when I downgrade sourcejs-react to 1.1.1.

**Comment by webuniverseio** [comment]
The reason why it complains about `<` is because required files are not being processed by babel. To make that happen you need to [specify](https://github.com/szarouski/sourcejs-react#options) file patterns which babel should process. I was able to reproduce your issue by checking out example-specs-showcase repository and the reason why it was breaking for me is because I was loading spec page from /user/react folder, while by default plugin supports only /user/specs/*\* paths, so following settings worked for me:

``` js
plugins: {
    react: {
        babel: {
            ignore: /.*/,
            only: ['**/user/{specs,react}/**']
        }
    }
}
```

Also keep in mind that if you're using `example-specs-showcase` repository, you'll have to change `sourcejs-react/node_modules/react/addons` paths to be just `react` (showcase repo got a bit out-of-date). 

I'm not 100% sure if that is your case, because based on the stack trace it looks like you put files under specs folder, so things should be working out of the box. If you would like additional help, please send me your `styleguide` folder (if you have some sensitive data in this folder, please clean it up).

Thank you.
